export const API_ENDPOINTS = {
    LOGIN: "/auth/login",
    REGISTER: "/auth/signup",
    SENDWHATSAPPOTP: "/auth/send-otp",
    VERIFYWHATSAPPOTP: "/auth/verify-otp",
    UPDATEUSERPIN: "/auth/update-user-pin",
    USERPROFILEUPDATE: "/auth/user/update",
    CHECKPROFILECOMPLETED: "/vendor-profile/check-profile-completed",
    GOOGLE_GEOCODE: "/geocode/json",
    GOOGLE_PLACE_DETAILS: "/place/details/json",
    GOOGLE_AUTOCOMPLETE: "/place/autocomplete/json",
    PLANSGETALL: "/plans/getall",
    PAYMENTMETHODSGETALL: "/paymentmethod/getall",
    BRANDSGETALL: "/brand/getall",
    BRANDSGETBYID: "/brand/get",
    BRANDUPDATE: "/brand/update",
    BRANDCREATE: "/brand/create",
    VENDORPROFILEGET: "/vendor-profile/get",
    VENDORPROFILEUPDATE: "/vendor-profile/update",
    VENDORPROFILECREATE: "/vendor-profile/create",
    VENDORCOUPONSGETALL: "/vendorcoupon/getall",
    VENDORCOUPONCREATE: "/vendorcoupon/create",
    VENDORCOUPONUPDATE: "/vendorcoupon/update",
    VENDORCOUPONGETBYID: "/vendorcoupon/get",
    VENDORCOUPONGETBYVENDORID: "/vendorcoupon/vendor",
    GETALLPRODUCTS: "/product/getall",
    CREATEPRODUCT: "/product/create",
    UPLOADPRODUCTIMAGE: "/product/image/upload",
    UPLOADPRODUCTVARIANTIMAGE: "/product/variant/image/upload",
    UPLOADPRODUCTVIDEO: "/product/video/upload",
    GETALLPRODUCTCATEGORIES: "/productcategory/getall",
    GETALLVENDORCATEGORIES: "/vendorcategory/getall",
    GETALLUNITS:"/unit/getall",
    GETALLGSTRULES:"/gstrule/getall",
    GETALLVARIANTS:"/productvariant/getall",
    PAYMENTTRANSACTIONCREATE:"/paymenttransaction/create",
    PAYMENTTRANSACTIONVERIFY:"/paymenttransaction/verify",
    VENDORSUBSCRIPTIONGETALL:"/vendorsubscription/getall",
    VENDORSUBSCRIPTIONGETBYUSER:"/vendorsubscription/getbyuser",
    VENDORDASHBOARDCOUNTSGETALL:"/vendordashboard/counts",
    VENDORPROFILEKYCCHECK:"/vendor-profile/checkkyc",
    VENDORKYCDOCUMENTSUPLOAD:"/vendor-profile/kycdocuments/upload",
    GETALLPRODUCTCATEGORIESBYVENDORCATEGORY: "/productcategory/getbyvendorcategory",


}